#!/usr/bin/env python3
"""Regenerate the self-hosted Devicon subset.

The Technologies section uses ~35 of Devicon's ~1,000 glyphs. Loading the full icon font from a CDN
cost 1.5 MB + 130 KB of CSS; this script keeps only the glyphs referenced in
components/TechnologiesSection.vue (12 KB woff2 + 4 KB CSS) and pins the Devicon version.

Run it after adding or removing a `devicon-*` class in TechnologiesSection.vue:

    pip install fonttools brotli
    python scripts/build-devicon-subset.py

Outputs (commit both):
    assets/fonts/devicon-subset.woff2
    assets/css/devicon-subset.css
"""
import os
import re
import sys
import urllib.request

from fontTools import subset
from fontTools.ttLib import TTFont

DEVICON_VERSION = "2.17.0"
CDN = f"https://cdn.jsdelivr.net/npm/devicon@{DEVICON_VERSION}"

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
COMPONENT = os.path.join(ROOT, "components", "TechnologiesSection.vue")
FONT_OUT = os.path.join(ROOT, "assets", "fonts", "devicon-subset.woff2")
CSS_OUT = os.path.join(ROOT, "assets", "css", "devicon-subset.css")


def fetch(url):
    with urllib.request.urlopen(url) as r:
        return r.read()


def main():
    used = sorted(set(re.findall(r"devicon-[a-z0-9-]+", open(COMPONENT, encoding="utf-8").read())))
    css = fetch(f"{CDN}/devicon.min.css").decode("utf-8-sig")

    codepoints, colors = {}, {}
    for selectors, body in re.findall(r"([^{}@]+)\{([^{}]*)\}", css):
        names = [s.strip() for s in selectors.split(",")]
        content = re.search(r'content:"(.)"', body)
        color = re.search(r"(?:^|;)color:(#[0-9a-fA-F]{3,8})", body)
        for name in names:
            if content and name.endswith(":before"):
                codepoints[name[1:-len(":before")]] = ord(content.group(1))
            elif color and name.endswith(".colored"):
                colors[name[1:-len(".colored")]] = color.group(1)

    missing = [u for u in used if u not in codepoints or u not in colors]
    if missing:
        sys.exit(f"Not found in devicon@{DEVICON_VERSION}: {missing}")

    ttf_path = os.path.join(ROOT, ".devicon-full.ttf.tmp")
    with open(ttf_path, "wb") as f:
        f.write(fetch(f"{CDN}/fonts/devicon.ttf"))
    try:
        opts = subset.Options()
        opts.flavor = "woff2"
        opts.layout_features = []
        opts.name_IDs = [1, 2]
        opts.notdef_outline = False
        opts.glyph_names = False
        opts.hinting = False
        font = TTFont(ttf_path)
        subsetter = subset.Subsetter(opts)
        subsetter.populate(unicodes=[codepoints[u] for u in used])
        subsetter.subset(font)
        font.flavor = "woff2"
        os.makedirs(os.path.dirname(FONT_OUT), exist_ok=True)
        font.save(FONT_OUT)
    finally:
        os.remove(ttf_path)

    lines = [
        f"/* Subset of Devicon {DEVICON_VERSION} (MIT, https://devicon.dev) - only the glyphs used by TechnologiesSection.vue.",
        "   Generated by scripts/build-devicon-subset.py - re-run it when the icon list changes. */",
        '@font-face{font-family:"devicon";src:url("../fonts/devicon-subset.woff2") format("woff2");font-weight:normal;font-style:normal;font-display:block}',
        '[class^=devicon-],[class*=" devicon-"]{font-family:"devicon" !important;speak:never;font-style:normal;font-weight:normal;font-variant:normal;text-transform:none;line-height:1;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}',
    ]
    lines += [".%s:before{content:\"\\%x\"}" % (u, codepoints[u]) for u in used]
    lines += [".%s.colored{color:%s}" % (u, colors[u]) for u in used]
    with open(CSS_OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"{len(used)} icons -> {os.path.relpath(FONT_OUT, ROOT)} ({os.path.getsize(FONT_OUT)} bytes), "
          f"{os.path.relpath(CSS_OUT, ROOT)} ({os.path.getsize(CSS_OUT)} bytes)")


if __name__ == "__main__":
    main()
